### ISSUE TITLE
missing gulp-util dependency

### ISSUE THREAD

**Issue by step21** [sat-metalab/scenic#76]
Without manually installing gulp-util (npm -g install gulp-util) the build process (make build) cannot succeed.

**Comment by francoisph** [comment]
Hey! You don't need to install manually gulp-util, this package is automatically installed with the package gulp. You may have an older version of gulp, try to remove the node_modules folder and run again npm install.

**Comment by step21** [comment]
Hej, well but gulp afaik was also not set as dependency? I will check when I try it again.

**Comment by nicobou** [comment]
By the way, was is your OS ? (The current version has been tested with Ubuntu 16.04 & Mint 18.)

**Comment by step21** [comment]
My OS for this test was Ubuntu 16.04, almost freshly installed. Next I also wanted to try the docker file .... does that work well?

**Comment by paperManu** [comment]
Hi step21,

I just tried doing the whole installation process of the develop branches on a clean docker container, running Ubuntu 16.04, and I had no issue. Note that there is currently an issue in the master branch.

Here is what I did:
```
docker run -ti ubuntu:16.04 /bin/bash
cd ~
apt install git
git clone https://github.com/sat-metalab/libshmdata
git clone https://github.com/sat-metalab/switcher
git clone https://github.com/sat-metalab/scenic
# Install Shmdata
cd libshmdata && git checkout develop
apt install automake bison build-essential flex libtool install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev install python3-dev
./autogen.sh && ./configure
make -j && sudo make install
cd ..

# Install switcher
cd switcher && git checkout develop
apt-get install automake bison build-essential flex libtool libglib2.0-devlibgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libjson-glib-dev libcgsi-gsoap-devgstreamer1.0-libav gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly liblo-dev linux-libc-dev libgtk-3-dev libpulse-dev libportmidi-dev libjack-jackd2-dev libvncserver-dev

# Install scenic
cd scenic && git checkout develop
apt install nodejs nodejs-legacy npm chromium-browser
npm install
make build
make install

# Run scenic
scenic
```

This should work in a docker container. If it does, you can then try installing it in the host system.

**Comment by step21** [comment]
Thanks for the detailed workflow. I will try it as soon as possible.

**Comment by step21** [comment]
Also, just to clarify eventually I managed to build with manually installing gulp/gulp-util globally. However, if you look at the other issue ( #77 ) I created, I then get an issue about server.js not being found.

**Comment by paperManu** [comment]
I did not have to install anything in addition to what is specified in the documentation of the various sources. Maybe your issue is related to something in your configuration?

**Comment by step21** [comment]
@paperManu thanks, it worked now, though your example was missing at least two ./autogen.sh && .configure
