### ISSUE TITLE
scenic does not find server.js after 'make install'

### ISSUE THREAD

**Issue by step21** [sat-metalab/scenic#77]
Installation went fine, all dependencies installed.
When starting I get: "Cannot find module '/usr/share/scenic/server.js"
In '/usr/share/scenic/' there are the folders npm_modules and public. Server stuff is in ./server of the source tree, but if I copy that directly to /usr/share/scenic as it seems to expect, this just leads to follow up errors. So what is going wrong?

**Comment by francoisph** [comment]
Can you try to do 'npm install switcher' ?Do you have errors ?

**Comment by step21** [comment]
solved on a fresh install, with all branches set to 'develop' as suggested in other thread
